Test/n12
DnbDnbMda/TMS_FM pull request #14
Opened 2024-10-26 23:17 UTC by DnbDnbMda

Реализованы тесты с покрытием 86% строк.

2024-10-29 11:50 UTC, ProfffUndo requested changes

2024-10-29 11:50 UTC, ProfffUndo commented on pom.xml
> +            <scope>test</scope>
Нужно все на юпитере было делать, не зря же есть страница с совместимыми версиями
https://docs.spring.io/spring-boot/docs/3.2.3/reference/html/dependency-versions.html#appendix.dependency-versions

2024-10-29 11:50 UTC, ProfffUndo commented on src/main/resources/application.yaml
> +spring:
У тебя уже выше открыто дерево spring, не нужно еще одно создавать

2024-10-29 11:50 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationDtoTest.java
> +    public void testGetterOrganizationDto() {
Ну вот такие тесты не нужны, это уже слишком. Геттеры, сеттеры проверять не надо.

2024-10-29 11:50 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationDtoTest.java
> +    public void testGetterOrganizationDto() {
В целом класс можно удалить этот

2024-10-29 11:50 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationMapperTest.java
> +    public void testMapToOrganizationNullOrgDto() {
Лишний тест, повтор того что выше.

2024-10-29 11:50 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationMapperTest.java
> +    public void testMapToOrganizationDtoNullOrg() {
Лишний тест, повтор того что выше.

2024-10-29 11:50 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationServiceTest.java
> +public class OrganizationServiceTest {
Где мокито тесты? Добавь в отдельный тестовый класс тогда, то что мы писали.

2024-11-03 07:39 UTC, DnbDnbMda commented on pom.xml
> +            <scope>test</scope>
Изменил зависимость на JUnit Jupiter.

2024-11-03 07:44 UTC, DnbDnbMda commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationDtoTest.java
> +    public void testGetterOrganizationDto() {
С одной стороны согласен, но с другой стороны я столкнулся, когда при использовании аннотации @Data метода toString() выбрасывал ошибку, когда поля класса равнялись null. По этому решил перестраховаться.

2024-11-03 07:51 UTC, DnbDnbMda commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationMapperTest.java
> +    public void testMapToOrganizationNullOrgDto() {
Хорошее замечание. Удалил.

2024-11-03 09:02 UTC, DnbDnbMda commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationMapperTest.java
> +    public void testMapToOrganizationDtoNullOrg() {
Удалил дублирующий метод

2024-11-03 10:53 UTC, DnbDnbMda commented on src/main/resources/application.yaml
> +spring:
По другому у меня не получилось сделать тестовый профиль "on-profile: test", который вызывается при выполнении тестов с базой H2. Можем обсудить.

2024-11-03 22:42 UTC, DnbDnbMda commented on src/test/java/com/reroute/tmsfm/testOrganization/OrganizationServiceTest.java
> +public class OrganizationServiceTest {
Сделал на данном этапе частичное покрытие.

2024-11-04 08:37 UTC, merged