Feature/№1
DnbDnbMda/TMS_FM pull request #4
Opened 2024-06-21 10:09 UTC by DnbDnbMda

2024-07-04 23:30 UTC, DnbDnbMda commented
Частично доработал функционал. Есть вопросы, которые застопорили.

2024-07-11 22:21 UTC, ProfffUndo commented
Переименовать PR с Feature/№1 - в названии должно быть наименование задачи тоже

2024-07-11 23:24 UTC, ProfffUndo requested changes
Не каждое замечание нужно править, можно обосновать свое решение, если я с ним соглашусь, то можно оставить.
Самое главное - написать тесты.

2024-07-11 23:24 UTC, ProfffUndo commented on desktop.ini
Что это за файл? Не могу понять)

2024-07-11 23:24 UTC, ProfffUndo commented on pom.xml
> +    <name>TMS_Fleet_Management</name>
Нижние подчеркивания в названиях редко используются, так же как и капс. Я бы сделал tsm-fleet-management

2024-07-11 23:24 UTC, ProfffUndo commented on pom.xml
> +    <description>TMS_FM Project</description>
Переписать описание, должно быть кратко, но понятно.

2024-07-11 23:24 UTC, ProfffUndo commented on pom.xml
> +    <dependencies>
Сгруппировать зависимости, можно использовать комментарии для разделения блоков, например отделить блок спринга

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @PostMapping(value = \"/organization\"), {}", organizationDto);
Идея хорошая, но 

1. Не нужно писать аннотацию с со всеми параметрами POST /organisation достаточно
2. Нужно еще сделать на уровне info лог, в котором выводился бы просто id новой записи, если он уже сформирован на этот момент
3. И сделать так чтобы информация в debuge не дублироваась

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @PatchMapping(value = \"/organization\") {}", organizationDto);
Аналогично create

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization/all\")");
Аналогично create

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization\")");
Аналогично create

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization\")");
И лучше все в одном методе сделать, не надо делить на 2.
Но сделать так чтобы было сначала
log.info
а потом
log.debug

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization\") в контроллере getOrganizationById {}",
Аналогично create

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @DeleteMapping(value = \"/organization/{organizationId}\") {}", organizationId);
Аналогично create

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +    public ResponseEntity<Object> handleConstraintViolationException(ConstraintViolationException ex) {
Нужно объяснить что это такое, зачем оно здесь, и если все же оставляем, то нужно в отдельной папке handler все это хранить.

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String id;
Если приходит UUID, то нужно и тип UUID делать а не String

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String id;
родителя тоже касается

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String name;
Не нужно 3 констрейнта, оставить 1
https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private LocalDateTime createdDate;
Всю информацию которая непосредственно к логике организации не имеет отношения, нужно вынести в отдельный абстрактный класс, чтобы в каждом dto это не писать

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String inn;
Важен порядок расположения полей. inn и kpp намного важнее чем changeAuthor. Я бы их сразу после id делал

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    @org.hibernate.validator.constraints.UUID(message = "Неккорректный идентфиикатор организации владельца")
Ну да, здесь точно от всех этих констрейнтов нужно избавляться, не нужная штука. Достаточно просто поставить везде тип UUID

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/entity/Account.java
> +    private LocalDate birthday;
Нужно в проекте использовать один тип времени LocalDateTime  и LocalDate - разные типы . LocalDateTime - хороший вариант.

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private Boolean group;
можно сделать просто boolean, тогда и констрейнт не нужен. Ко всему проекту относится

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/entity/Account.java
> +    private Account author;
Давай мы во всех классах, в дто и т.д. пока что выпилим все что связано с авторами объектов, создателями их и изменениями, кроме даты создания. Это нужно делать по другому, потом заведем задачу

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/entity/Organization.java
> +@AllArgsConstructor
Да просто сразу аннотацию `@Data` ставить и все. Не нужно это все расписывать, к тому же тогда не нужно toString перегружать. Ко всем классам относится

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/entity/Organization.java
> +    private Organization ownerOrganization;
Что за поле? У организации есть владелец организации или организация-владелец и чем это от родителя отличается?

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/mapper/OrganizationMapper.java
> +    class Utils {
класс Utils норм, но не нужно делать его внутренним. Заимпортить его можно в аннотации `@Mapper(import=...)`

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/mapper/OrganizationMapper.java
> +            return source.getOwnerOrganization() == null ? null : source.getOwnerOrganization().getId().toString();
Использовать Optional

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/AccountService.java
> +public interface AccountService {
`@Service`

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +                log.error("Организация с идентификатором {} уже существует", organizationDto.getId());
Это не error, это штатная работа. Error - то если что-то пошло не по нашему плану

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        organizationDto.setCreatedDate(LocalDateTime.now());
Весь маппинг в маппере. Если нужно можно использовать default методы там.

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        organizationDto.setCreatedDate(LocalDateTime.now());
Все блоки с if и прочее, отсюда тоже убрать это все в маппере должно происходить

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        log.debug("Подготовлен organizationDto для передачи в mapper {}", organizationDto);
Не должно быть подготовки, максимум валидация аннотациями, ты берешь то dto которое пришло сразу кидаешь в mapper, если там какие-то ошибки, ловишь exception и отдаешь.

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        Organization organization = organizationMapper.toOrganization(organizationDto,
Вся инфа которую ты раскапываешь она есть в organizationDto, поэтому в маппер мы передаем только его, а внутри уже развлекаемся. Опять же лучше для начала убрать все ownerOrg, parentOrg, createAuthor. Потом отдельными фичами сделаем.

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        log.info("В БД добавлена новая организация {}", createdOrganization);
не нужно все дто в info кидать, достаточно id

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        log.info("В БД добавлена новая организация {}", createdOrganization);
Можно в debug если очень хочется

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        return Optional.of(organizationMapper.toOrganizationDto(createdOrganization));
Не очень понимаю зачем в возвращаемом значении Optional

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/utility/AccountStatus.java
> +public enum AccountStatus {
отдельная папка enums

2024-07-11 23:24 UTC, ProfffUndo commented on src/main/java/com/reroute/tmsfm/utility/PageConfig.java
> +public class PageConfig extends PageRequest {
Не нужный класс пока что особенно учитывая
`PageRequest pageRequest = new PageConfig(from, size, Sort.unsorted());`

2024-07-11 23:24 UTC, ProfffUndo commented on src/test/java/com/reroute/tmsfm/TmsFleetManagementApplicationTests.java
>  import org.springframework.boot.test.context.SpringBootTest;
Самое главное замечание - нет тестов. Любой функционал должен быть покрыт тестами. В идеале это 80 процентов, но понимаю что по началу тяжело, так что остановимся на 60 процентах кода.

2024-07-13 14:03 UTC, DnbDnbMda commented on desktop.ini
fix: Удален системный файл Windows

2024-07-13 15:45 UTC, DnbDnbMda commented on pom.xml
> +    <name>TMS_Fleet_Management</name>
fix: исправлено наименвоание и описание проекта в pom

2024-07-13 15:45 UTC, DnbDnbMda commented on pom.xml
> +    <description>TMS_FM Project</description>
fix: исправлено наименование и описание проекта в pom

2024-07-13 16:26 UTC, DnbDnbMda commented on pom.xml
> +    <dependencies>
fix: сгруппированы зависимости в pom

2024-07-13 16:27 UTC, DnbDnbMda commented on pom.xml
> +    <dependencies>
По какому приницпу лучше группировать?

2024-07-13 18:32 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @PostMapping(value = \"/organization\"), {}", organizationDto);
fix: исправлены методы логирования создания организации.
Логирование нового идентификатора сделал в сервисе

2024-07-13 18:42 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @PatchMapping(value = \"/organization\") {}", organizationDto);
fix: исправлены методы логирования обновления организации

2024-07-13 19:00 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization/all\")");
fix: исправлены методы логирования в контроллере организации

2024-07-13 19:01 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization\")");
fix: исправлены методы логирования в контроллере организации

2024-07-13 19:01 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @GetMapping(value = \"/organization\") в контроллере getOrganizationById {}",
fix: исправлены методы логирования в контроллере организации

2024-07-13 19:11 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/controller/OrganizationController.java
> +        log.debug("Получен запрос @DeleteMapping(value = \"/organization/{organizationId}\") {}", organizationId);
fix: исправлены методы логирования в контроллере организации

2024-07-14 06:30 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/entity/Account.java
> +    private LocalDate birthday;
fix: исправлены типы и аннотации в классе Account

2024-07-14 06:57 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    @org.hibernate.validator.constraints.UUID(message = "Неккорректный идентфиикатор организации владельца")
1. Искал возможность проверять UUID на корректность. Нашёл класс который в принципе решает эту задачу по многим параметрам, но он работает только с последовательностью символов.

2024-07-14 07:19 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private Boolean group;
fix: исправлены типы, ограничения и аннотации в классе OrganizationDto.

2024-07-14 08:04 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/entity/Account.java
> +    private Account author;
fix: удалены поля в классах создателей и редакторов объекта и удален соответствующий код

Необходимо обсудить на встрече

2024-07-14 08:15 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/entity/Organization.java
> +@AllArgsConstructor
fix: оптимизированы аннотации lombok

Метод toString переопределял из-за того, что у меня возникали ситуации с выбрасыванием null pointer exception

2024-07-14 20:03 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        Organization organization = organizationMapper.toOrganization(organizationDto,
fix: полностью удалены поля родители и собственники организации.

Всё полностью удалил.

2024-07-14 20:08 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/service/AccountService.java
> +public interface AccountService {
fix: добавил аннотацию Service

2024-07-14 20:13 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String id;
Ответил в комментарии [(https://github.com/DnbDnbMda/TMS_FM/pull/4#discussion_r1674800484)]

2024-07-14 20:29 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/dto/OrganizationDto.java
> +    private String inn;
fix: изменил последовательность полей класса.

2024-07-14 21:12 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/entity/Organization.java
> +    private Organization ownerOrganization;
"Родитель" - это поле для указания той записи базы данных, которая является верхнеуровневой. Данное поле необходимо в том случае, если для ведения какой либо справочной информации необходима возможность учета иерархии записей. Планирую в рамках своего проекта использовать два типа способа организации учета справочной информации: "Иерархия элементов" и "Иерархия групп и элементов". Второй тип организации учета справочной информации подразумевает использование групп в которые можно разместить определенные записи.
Организация владелец - это признак по которому можно будет делать выборку только тех записей, которые относятся к конкретной организации. В моей концепции, что в данном сервисе будут регистрироваться множество компаний, которые будут вести свою собственную справочную информацию, которая не должна быть доступна для прочих организаций.
Можем обсудить.

2024-07-14 21:13 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/mapper/OrganizationMapper.java
> +    class Utils {
Пока потребность в данном классе пропала, так как исключили поля собственник, родитель и т.д.

2024-07-15 20:25 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/utility/AccountStatus.java
> +public enum AccountStatus {
fix: перечисление статусов вынесено в отдельную папку enums

2024-07-15 20:30 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/mapper/OrganizationMapper.java
> +            return source.getOwnerOrganization() == null ? null : source.getOwnerOrganization().getId().toString();
Пока потребность в данном исправлении пропала, так как пока удалил эту функциональность.

2024-07-15 20:41 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/service/OrganizationServiceImpl.java
> +        return Optional.of(organizationMapper.toOrganizationDto(createdOrganization));
public static <T> ResponseEntity<T> of(Optional<T> body)

2024-07-15 21:02 UTC, DnbDnbMda commented on src/main/java/com/reroute/tmsfm/utility/PageConfig.java
> +public class PageConfig extends PageRequest {
fix: оптимизирован код для создания pageRequest

2024-07-31 20:56 UTC, merged